dist: trusty
sudo: required

services: docker

language: bash

branches:
  only:
    - master

before_script:
  - env | sort
  - dir="images/${VERSION}/${VARIANT}"

script:
  - cd "$dir"
  # Test containers build
  - travis_retry docker-compose build
  # Test containers run
  - docker-compose up -d && sleep 60
  - docker-compose ps
  - docker-compose logs
  - docker-compose ps "taiga_back" | grep "Up"
  - docker-compose ps "taiga_front" | grep "Up"
  # Test containers can be dropped and restarted
  - docker-compose down
  - docker-compose up -d && sleep 60
  - docker-compose ps
  - docker-compose logs
  - docker-compose ps "taiga_back" | grep "Up"
  - docker-compose ps "taiga_front" | grep "Up"
  # Drop containers and check they restart properly
  - docker-compose down
  - travis_retry docker-compose up -d && sleep 60

after_script:
  - docker images
  - docker ps -a

notifications:
  email: false

env: # Environments
    - VERSION=3.3 VARIANT=alpine
    - VERSION=3.4 VARIANT=alpine
    - VERSION=4.0 VARIANT=alpine
    - VERSION=4.1 VARIANT=alpine
    - VERSION=4.2 VARIANT=alpine
