version: '2'

services:
  # Taiga service
  taigadb:
    image: postgres:10-alpine
    container_name: taigadb
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /srv/taiga/db/data:/var/lib/postgresql/data
    environment:
        - POSTGRES_DB=taiga
        - POSTGRES_USER=taiga
        - POSTGRES_PASSWORD=${TAIGA_DB_PWD}

  taigaback:
    build: ./back
    #image: monogramm/docker-taiga-back:3.4-alpine
    container_name: taigaback
    restart: always
    depends_on:
      - taigadb
    ports:
      - 8000:8000
    volumes:
      # Media and uploads directory. Required (or you will lose all uploads)
      - /srv/taiga/back/media:/usr/src/taiga-back/media
      # Taiga configuration directory. Makes it easier to change configuration with your own
      #- /srv/taiga/back/conf:/taiga
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      # Your hostname (REQUIRED)
      - TAIGA_HOSTNAME=taiga.${DOMAIN}
      #- TAIGA_SSL=False
      #- TAIGA_SSL_BY_REVERSE_PROXY=True
      # Secret key for cryptographic signing
      - TAIGA_SECRET_KEY=${TAIGA_SECRET}
      # Database settings
      - TAIGA_DB_HOST=taigadb
      - TAIGA_DB_NAME=taiga
      - TAIGA_DB_USER=taiga
      - TAIGA_DB_PASSWORD=${TAIGA_DB_PWD}
      # when the db comes up from docker, it is usually too quick
      - TAIGA_SLEEP=15
      # To use an external SMTP for emails, fill in these values:
      - TAIGA_ENABLE_EMAIL=True
      - TAIGA_EMAIL_FROM=taiga@${TAIGA_EMAIL_DOMAIN}
      - TAIGA_EMAIL_USE_TLS=True
      - TAIGA_EMAIL_HOST=smtp.${TAIGA_EMAIL_DOMAIN}
      - TAIGA_EMAIL_PORT=587
      - TAIGA_EMAIL_USER=${TAIGA_SMTP_USER}
      - TAIGA_EMAIL_PASS=${TAIGA_SMTP_PWD}
      # Backend settings
      - TAIGA_DEBUG=False
      - TAIGA_PUBLIC_REGISTER_ENABLED=False
      # Events settings
      #- RABBIT_HOST=taigarabbit
      #- REDIS_HOST=taigaredis
      # Slack
      - TAIGA_ENABLE_SLACK=True
      # GitLab
      - TAIGA_ENABLE_GITLAB=True
      - TAIGA_GITLAB_URL=${TAIGA_GITLAB_URL}
      - TAIGA_GITLAB_CLIENT_ID=${TAIGA_GITLAB_CLIENT_ID}
      - TAIGA_GITLAB_CLIENT_SECRET=${TAIGA_GITLAB_CLIENT_SECRET}
      # GitHub
      - TAIGA_ENABLE_GITHUB=True
      - TAIGA_GITHUB_CLIENT_ID=${TAIGA_GITHUB_CLIENT_ID}
      - TAIGA_GITHUB_CLIENT_SECRET=${TAIGA_GITHUB_CLIENT_SECRET}
      # LDAP Settings
      - TAIGA_ENABLE_LDAP=True
      - TAIGA_LDAP_USE_TLS=True
      - TAIGA_LDAP_SERVER=ldap://${TAIGA_LDAP_DOMAIN}
      - TAIGA_LDAP_PORT=389
      - TAIGA_LDAP_BIND_DN=${TAIGA_LDAP_BIND_DN}
      - TAIGA_LDAP_BIND_PASSWORD=${TAIGA_LDAP_BIND_PASSWORD}
      - TAIGA_LDAP_BASE_DN=${TAIGA_LDAP_BASE_DN}
      - TAIGA_LDAP_USERNAME_ATTRIBUTE=uid
      - TAIGA_LDAP_EMAIL_ATTRIBUTE=mail
      - TAIGA_LDAP_FULL_NAME_ATTRIBUTE=cn
      - TAIGA_LDAP_FALLBACK=normal

  taigafront:
    build: ./front
    #image: monogramm/docker-taiga-front:3.4-alpine
    hostname: taiga.${DOMAIN}
    container_name: taigafront
    restart: always
    depends_on:
      - taigaback
      # To enable taiga-events, uncomment the following lines:
      # - taigaevents
      # - taigarabbit
      # - taigaredis
    ports:
      - 80:80
      - 443:443
    volumes:
      # Taiga configuration directory. Makes it easier to change configuration with your own
      #- /srv/taiga/front/conf:/taiga
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      # Your hostname (REQUIRED)
      - TAIGA_HOSTNAME=taiga.${DOMAIN}
      #- TAIGA_SSL=True
      #- TAIGA_SSL_BY_REVERSE_PROXY=True
      # Frontend settings
      - TAIGA_DEBUG=false
      - TAIGA_DEBUG_INFO=false
      - TAIGA_DEFAULT_LANGUAGE=en
      - TAIGA_DEFAULT_THEME=taiga
      - TAIGA_PUBLIC_REGISTER_ENABLED=false
      - TAIGA_SUPPORT_URL=https://tree.taiga.io/support
      - TAIGA_PRIVACY_POLICY_URL=''
      - TAIGA_TOS_URL=''
      - TAIGA_GDPR_URL=''
      - TAIGA_MAX_UPLOAD_SIZE=104857600
      - TAIGA_CONTRIB_PLUGINS='slack cookie-warning'
      #- TAIGA_CONTRIB_PLUGINS='slack cookie-warning gitlab-auth github-auth'
      - TAIGA_GRAVATAR=true
      - TAIGA_LOGIN_FORM_TYPE=ldap
      # Backend settings
      - TAIGA_BACK_HOST=taigaback
      - TAIGA_BACK_PORT=8000
      # Events settings
      #- TAIGA_EVENTS_HOST=taigaevents
      #- TAIGA_EVENTS_PORT=8888
      #- RABBIT_PORT_5672_TCP_ADDR=True
      # GitLab
      - TAIGA_GITLAB_URL=${TAIGA_GITLAB_URL}
      - TAIGA_GITLAB_CLIENT_ID=${TAIGA_GITLAB_CLIENT_ID}
      # GitHub
      - TAIGA_GITHUB_CLIENT_ID=${TAIGA_GITHUB_CLIENT_ID}

  # To enable taiga-events, uncomment the following lines:
  # taigarabbit:
  #   image: rabbitmq:3
  #   hostname: rabbit
  # 
  # taigaredis:
  #   image: redis:3
  # 
  # taigacelery:
  #   image: celery
  #   links:
  #     - taigarabbit
  # 
  # taigaevents:
  #   image: benhutchins/taiga-events
  #   links:
  #     - taigarabbit
